---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
source(file.path("R", "00setup.R"))

library(magrittr)
here::set_here(getwd())

data_raw <- here::here("0data", "data_raw")
data_dir <- here::here("0data", "data_cleaned")
figurepath <- here::here("4figures")

# wrapper script for all data analyses and objects that required to render the
# manuscript and supplement
source(here::here("1analysis", "00wrapper_script.R"))
```

\newpage
{{< include 2manuscript_src/00abstract.qmd >}}
\newpage
{{< include 2manuscript_src/01introduction.qmd >}}
\newpage
{{< include 2manuscript_src/02methods.qmd >}}
\newpage
{{< include 2manuscript_src/03results.qmd >}}
\newpage
{{< include 2manuscript_src/04discussion.qmd >}}
\newpage
{{< include 2manuscript_src/05acknowledgements.qmd >}}
\newpage
{{< include 2manuscript_src/09references.qmd >}}

```{r}
# render supplement
source(here::here("3supplement", "prepare_supplement.R"))
quarto::quarto_render(
  input = here::here("3supplement", "supplement.qmd")
)
```

```{r}
# convert tiff to png
to_png <- list.files(figurepath)[endsWith(list.files(figurepath), ".tiff")]
png_path <- paste0(figurepath, "PNG/")
dir.create(png_path)
for (f in to_png) {
  img <- tiff::readTIFF(paste0(figurepath, f))
  png::writePNG(img, target=paste0(png_path, gsub("tiff$", "png", f)))
}
```

\newpage

# Tables {.unnumbered}

```{r}
#| include: true
#| label: tbl-data
#| tbl-cap: "Data"
#| column: body-outset

dat <- iris |>
  summary() |>
  knitr::kable()

if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "latex") {
  dat |>
  kableExtra::kable_styling(latex_options = "HOLD_position")
} else {
  dat
}
```

\newpage

# Figures {.unnumbered}

```{r}
#| include: true
#| label: fig-data
#| layout-ncol: 2
#| fig-cap: "Data plots."
#| fig-subcap:
#|   - "Sepal.Length vs. Sepal.Width."
#|   - "Petal.Length vs. Petal.Width"
#| out.width: "98%"
#| column: body-outset

plot(iris$Sepal.Length, iris$Sepal.Width)
plot(iris$Petal.Length, iris$Petal.Width)
```
